// Code generated by mockery v2.52.4. DO NOT EDIT.

package repository

import (
	context "context"

	model "github.com/radityacandra/ecommerce-connector-cli/internal/application/platform/model"
	repository "github.com/radityacandra/ecommerce-connector-cli/internal/application/platform/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// FindPlatformByUserIdAndType provides a mock function with given fields: _a0, _a1
func (_m *MockIRepository) FindPlatformByUserIdAndType(_a0 context.Context, _a1 repository.FindByUserIdAndTypeInput) (repository.FindByUserIdAndTypeOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindPlatformByUserIdAndType")
	}

	var r0 repository.FindByUserIdAndTypeOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindByUserIdAndTypeInput) (repository.FindByUserIdAndTypeOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindByUserIdAndTypeInput) repository.FindByUserIdAndTypeOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(repository.FindByUserIdAndTypeOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.FindByUserIdAndTypeInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_FindPlatformByUserIdAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPlatformByUserIdAndType'
type MockIRepository_FindPlatformByUserIdAndType_Call struct {
	*mock.Call
}

// FindPlatformByUserIdAndType is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repository.FindByUserIdAndTypeInput
func (_e *MockIRepository_Expecter) FindPlatformByUserIdAndType(_a0 interface{}, _a1 interface{}) *MockIRepository_FindPlatformByUserIdAndType_Call {
	return &MockIRepository_FindPlatformByUserIdAndType_Call{Call: _e.mock.On("FindPlatformByUserIdAndType", _a0, _a1)}
}

func (_c *MockIRepository_FindPlatformByUserIdAndType_Call) Run(run func(_a0 context.Context, _a1 repository.FindByUserIdAndTypeInput)) *MockIRepository_FindPlatformByUserIdAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.FindByUserIdAndTypeInput))
	})
	return _c
}

func (_c *MockIRepository_FindPlatformByUserIdAndType_Call) Return(_a0 repository.FindByUserIdAndTypeOutput, _a1 error) *MockIRepository_FindPlatformByUserIdAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_FindPlatformByUserIdAndType_Call) RunAndReturn(run func(context.Context, repository.FindByUserIdAndTypeInput) (repository.FindByUserIdAndTypeOutput, error)) *MockIRepository_FindPlatformByUserIdAndType_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *MockIRepository) Insert(_a0 context.Context, _a1 *model.Platform) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Platform) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockIRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *model.Platform
func (_e *MockIRepository_Expecter) Insert(_a0 interface{}, _a1 interface{}) *MockIRepository_Insert_Call {
	return &MockIRepository_Insert_Call{Call: _e.mock.On("Insert", _a0, _a1)}
}

func (_c *MockIRepository_Insert_Call) Run(run func(_a0 context.Context, _a1 *model.Platform)) *MockIRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Platform))
	})
	return _c
}

func (_c *MockIRepository_Insert_Call) Return(_a0 error) *MockIRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_Insert_Call) RunAndReturn(run func(context.Context, *model.Platform) error) *MockIRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
