// Code generated by mockery v2.52.4. DO NOT EDIT.

package client

import (
	context "context"

	model "github.com/radityacandra/ecommerce-connector-cli/internal/application/product/model"
	mock "github.com/stretchr/testify/mock"
)

// MockProductClient is an autogenerated mock type for the ProductClient type
type MockProductClient struct {
	mock.Mock
}

type MockProductClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductClient) EXPECT() *MockProductClient_Expecter {
	return &MockProductClient_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function with given fields: ctx, product
func (_m *MockProductClient) AddProduct(ctx context.Context, product model.Product) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Product) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductClient_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockProductClient_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product model.Product
func (_e *MockProductClient_Expecter) AddProduct(ctx interface{}, product interface{}) *MockProductClient_AddProduct_Call {
	return &MockProductClient_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, product)}
}

func (_c *MockProductClient_AddProduct_Call) Run(run func(ctx context.Context, product model.Product)) *MockProductClient_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Product))
	})
	return _c
}

func (_c *MockProductClient_AddProduct_Call) Return(_a0 error) *MockProductClient_AddProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductClient_AddProduct_Call) RunAndReturn(run func(context.Context, model.Product) error) *MockProductClient_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductClient creates a new instance of MockProductClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductClient {
	mock := &MockProductClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
